### ISSUE TITLE
MVP-2 Review Request 

### ISSUE THREAD

**Issue by Emina288** [Emina288/GoodreadsFullStack#5]
-Welcome container for the Splash page that holds Login Component, Signup Component as well as the Footer Component and Main Content Component.
-Demo button where users can login to try out the site. 
-Home Container where users get redirected on a successful login and where users can log out and go back on the splash page.

**Comment by jliversi** [comment]
Nice work on your first MVP, here are my notes:
FUNCTIONALITY
- [ ] Remove the "Continue with Facebook" and "Continue with Amazon" buttons on your sign-in page and sign-up pages. One of these buttons can become a "Demo Login" button.
- [ ] Include links on each session form to reach the other session form (just like Goodreads has).
- [ ] Remove "you can reset password" from errors (as your site doesn't have this functionality). 
- [ ] Remove App Store and Google Play links in footer

STYLING
- [ ] Your forms will be shorter than the ones on Goodreads because you'll lose one of the facebook/amazon buttons, and won't have terms/conditions below. Instead of aiming to have the same height, aim to have the same spacing around the form. So the bottom content should have the same ~40px below it before the white box of the form ends. 
- [ ] Clean up your dropdown (where the logout button is located) to look exactly like goodreads'. `
